### ISSUE TITLE
Implementación de microservicios y configuración de kubernetes

### ISSUE THREAD

**Issue by SEAL2201** [Puce99/S-ndwich#17]

**Comment by neithanmervil** [comment]
Configurar un clúster de Kubernetes que utilice Docker como contenedor para soportar el servicio de entrega a domicilio de pedidos de sándwiches. Esta tarea implica la preparación y configuración de la infraestructura necesaria para asegurar la disponibilidad y escalabilidad del sistema en respuesta a las necesidades fluctuantes de pedidos y entregas.
