### ISSUE TITLE
Tiempo de recolección

### ISSUE THREAD

**Issue by neithanmervil** [Puce99/S-ndwich#3]

**Comment by neithanmervil** [comment]
Al momento de hacer el pedido, el sistema debe calcular una hora estimada de recogida basada en la carga de trabajo del local y la disponibilidad de los ingredientes. Un algoritmo de optimización puede ayudar a determinar este tiempo.

**Comment by MSBASTIAN1** [comment]
La hora de recolección se basa teniendo en cuenta el tiempo en el que se realiza el pedido del sandwich, para que se encuentre con la temperatura correcta.
